name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          echo "REACT_APP_WEATHER_API_KEY=${{ secrets.REACT_APP_WEATHER_API_KEY }}" > .env
          echo "REACT_APP_WAIFU_API_KEY=${{ secrets.REACT_APP_WAIFU_API_KEY }}" >> .env
          # Optional: Display the first few characters to verify the keys are set (without exposing full keys)
          echo "Weather API Key: ${REACT_APP_WEATHER_API_KEY:0:5}..."
          echo "Waifu API Key: ${REACT_APP_WAIFU_API_KEY:0:5}..."

      - name: Build React app
        run: npm run build

      - name: Upload build folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build 

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
